### ISSUE TITLE
Support deploying to GitHub releases

### ISSUE THREAD

**Issue by marco-c** [mozilla/task-boot#70]

**Comment by calixteman** [comment]
I added some code to upload the release on github:
https://github.com/mozilla/dump_syms/pull/44/files
And so it'd be nice to use taskboot for this project too.

**Comment by La0** [comment]
Here is the implementation i suggest: as we'll need the PyGithub module to use the Github API without implementing it ourselves, let's use it fully:

- A new command is added : `taskboot github-release <VERSION>`
- If the specified release does not already exists, it will create it
- It can use a previously built artifact as a release asset using the argument: `--asset=name:path/to/artifact.tar`
- It can set the release notes if a local target is available and `--publish-log` is specified (the first line of every commit since previous release will be used : that's what I do on code-review & code-coverage)

This behaviour would be used on taskboot itself too

**Comment by marco-c** [comment]
Sounds good to me. I'd make the release notes configurable too, maybe as a follow-up (by default what you said, and an option to use a file).

> If the specified release does not already exists, it will create it

If it already exists and a release asset already exists with the same name, what do we do? I think we should overwrite it.
